create table user_tokens (
           id int8 generated by default as identity,
           token varchar(255) not null,
           token_type varchar(20) not null,
           user_id int8 not null,
           revoked boolean default false,
           expired boolean default false,
           created_at timestamp,
           updated_at timestamp,
           primary key (id)
);

alter table if exists user_tokens
    add constraint FK_user_tokens_user
    foreign key (user_id)
    references users;