create table user_account_deposit (
          id int8 generated by default as identity,
          user_id int8 not null,
          deposit_value integer,
          reset boolean default false,
          created_at timestamp,
          updated_at timestamp,
          primary key (id)
);

alter table if exists user_account_deposit
    add constraint FK_user_account_deposit_user
    foreign key (user_id)
    references users;